void draw_compass(void);
void mark_wind(void);
void tumble_compass(int a);
int seek_heading(void);
void init_instruments(void);
void mark_hdg(int x);
void mark_wind(void);
int seek_prevailing(void);
void toggle_instrument_panel(void);
void take_hdg(void);
