#define MAX_BUFFER 50

/*
  "Goods" can be perishable items such as fruit, wood, wine, etc., or
  more traditional "products" such as weapons, clothing, barrels, etc.

*/
struct good_t {
        uint8_t type;
        uint32_t id;
        uint32_t buff;
        uint8_t rarity;
        uint8_t weight;
        uint8_t quality;
        uint8_t space;
        uint8_t spoil;
        char owner[MAX_BUFFER];
};


/*
  Food
*/

enum good_foods {FRUIT, VEGETABLE, NUT, SPICE, CEREAL};
enum food_nomen {COMMON,BINOMINAL};

static const char *goodname_fruit[]={
// A ------------------------------------------------------
{"Abiu"                  , "Pouteria caimito"             }, 
{"Açaí"                  , "Euterpe oleracea"             },
{"Acerola"               , "Malpighia glabra"             },
{"Ackee"                 , "Blighia sapida"               },
{"Ambarella"             , "Spondias dulcis"              },
{"Apple"                 , "Malus"                        },
{"Apricot"               , "Prunus armeniaca"             },
{"Araza"                 , "Eugenia stipitata"            },
{"Arhat"                 , "Siraitia grosvenorii"         },
{"Avocado"               , "Persea americana"             },
// B ------------------------------------------------------
{"Babaco"                , "Carica pentagona"             },
{"Bacupari"              , "Garcinia gardneriana"         },
{"Bacuri"                , "Platonia esculenta"           },
{"Bael"                  , "Aegle marmelos"               },
{"Banana"                , "Musacea spp."                 },
{"Barbadine"             , "granadilla"                   },
{"Beach Plum"            , "Prunus maritima"              },
{"Bearberry"             , "Arctostaphylos spp."          },
{"Betel Nut"             , "Areca catechu"                },
{"Bignay"                , "Antidesma bunius"             },
{"Bilberry"              , "Vaccinium spp."               },
{"Bilimbi"               , "Averrhoa bilimbi"             },
{"Biribi"                , "Rollinia deliciosa"           },
{"Black cherry"          , "Prunus serotina"              },
{"Black raspberry"       , "Rubus occidentalis"           },
{"Black Mulberry"        , "Morus nigra"                  },
{"Black Walnut"          , "Juglans nigra"                },
{"Blackberry"            , "Rubus"                        },
{"Blue tongue"           , "Melastoma affine"             },
{"Blueberry"             , "Vaccinium"                    },
{"Bolivian coconut"      , "Parajubaea torallyi"          },
{"Bolwarra"              , "Eupomatia laurina"            },
{"Boquila"               , "Boquila trifoliata"           },
{"Bottle Gourd"          , "Lagenaria siceraria"          },
{"Brazilian Guava"       , "Psidium guineense"            },
{"Breadnut"              , "Artocarpus camansi"           },
{"Broad-leaf Bramble"    , "Rubus moluccanus"             },
{"Buffaloberry"          , "Shepherdia argenta"           },
// C ------------------------------------------------------
{"Canistel"              , "Pouteria campechiana"         },
{"Cape Gooseberry"       , "Physalis peruviana"           },
{"Capuli cherry"         , "Prunus salicifolia"           },
{"Carambola"             , "Averrhoa carambola"           },
{"Cardón"                , "Pachycereus pringlei"         },
{"Carob"                 , "Ceratonia siliqua"            },
{"Cashew apple"          , "Anacardium occidentale"       },
{"Cassabanana"           , "Sicana odorifera"             },
{"Cawesh"                , "Annona scleroderma"           },
{"Ceriman"               , "Monstera deliciosa"           },
{"Chayote"               , "Sechium edule"                },
{"Che"                   , "Cudrania tricuspidata"        },
{"Chempedak"             , "Artocarpus integer"           },
{"Cherimoya"             , "Annona cherimola"             },
{"Cherry"                , "Prunus avium"                 },
{"Chokeberry"            , "Aronia"                       },
{"Chokecherry"           , "Prunus virginiana"            },
{"Chupa-Chupa"           , "Quararibea cordata"           },
{"Citron"                , "Citrus medica"                },
{"Cloudberry"            , "Rubus chamaemorus"            },
{"Cluster fig"           , "Ficus racemosa"               },
{"Coco Plum"             , "Chrysobalanus icaco"          },
{"Cocona"                , "Solanum sessilifolium"        },
{"Coconut"               , "Cocos nucifera"               },
{"Cocoplum"              , "Chrysobalanus icaco"          },
{"Coffee cherries"       , " "                            },
{"Cola nut"              , "Cola acuminata"               },
{"Common apple-berry"    , "Billardiera scandens"         },
{"Conkerberry"           , "Carissa lanceolata"           },
{"Cranberry"             , "Vaccinium spp."               },
{"Crowberry"             , "Empetrum spp."                },
{"Cupuaçu"               , "Theobroma grandiflorum"       },
{"Currant"               , "Ribes spp."                   },
{"Custard Apple"         , "Annona reticulata"            },
// D ------------------------------------------------------
{"Date"                  , "Phoenix dactylifera"          },
{"Date plum"             , "Diospyros lotus"              },
{"Dead Man's Fingers"    , "Decaisnea fargesii"           },
{"Desert banana"         , "Marsdenia australis"          },
{"Desert fig"            , "Ficus platypoda"              },
{"Desert lime"           , "Citrus glauca"                },
{"Dodder laurel"         , "Cassytha melantha"            },
{"Doubah"                , "Marsdenia australis"          },
{"Double Cocnut"         , "Lodoicea maldivica"           },
{"Dragonfruit"           , "Hylocereus spp."              },
{"Duku"                  , "Lansium domesticum"           },
{"Durian"                , "Durio zibethicus"             },
// E ------------------------------------------------------
{"Eastern May Hawthorn"  , "Crataegus aestivalis"         },
{"Elderberry"            , "Sambucus"                     },
{"Elephant Apple"        , "Dillenia indica"              },
{"Emu Apple"             , "Owenia acidula"               },
{"Emu berry"             , "Grewia retusifolia"           },
// F ------------------------------------------------------
{"Falberry"              , "Vaccinium spp."               },
{"False-mastic"          , "Sideroxylon foetidissimum"    },
{"Fibrous Satinash"      , "Syzygium fibrosum"            },
{"Fig"                   , "Ficus spp."                   },
{"Finger Lime"           , "Citrus australasica"          },
// G ------------------------------------------------------
{"Gambooge"              , "Garcinia cambogia"            },
{"Genip"                 , "Melicoccus bijugatus"         },
{"Giant Granadilla"      , "Passiflora quadrangularis"    },
{"Gooseberry"            , "Ribes spp."                   },
{"Goumi"                 , "Elaeagnus multiflora"         },
{"Governor’s Plum"       , "Flacourtia indica"            },
{"Grapefruit"            , "Citrus × paradisi"            },
{"Ground Plum"           , "Astragalus crassicarpus"      },
{"Grumichama"            , "Eugenia brasiliensis"         },
{"Guanabana"             , "Annona muricata"              },
{"Guarana"               , "Paullinia cupana"             },
{"Guava"                 , "Psidium guajava"              },
{"Guavaberry"            , "Myrciaria floribunda"         },
// H ------------------------------------------------------
{"Hackberry"             , "Celtis spp."                  },
{"Hardy Kiwi"            , "Actinidia arguta"             },
{"Hawthorn"              , "Crataegus"                    },
{"Horned melon"          , "Cucumis metuliferus"          },
{"Huito"                 , "Genipa americana"             },
// I ------------------------------------------------------
{"Ilama"                 , "Annona diversifolia"          },
{"Illawarra Plum"        , "Podocarpus elatus"            },
{"Imbe"                  , "Garcinia livingstonei"        },
{"Indian gooseberry"     , "Phyllanthus emblica"          },
{"Indian jujube"         , "Ziziphus mauritiana"          },
{"Indian prune"          , "Flacourtia rukan"             },
// J ------------------------------------------------------
{"Jaboticaba"            , "Myrciaria cauliflora"         },
{"Jackfruit"             , "Artocarpus heterophyllus"     },
{"Jambul"                , "Syzygium cumini"              },
{"Japanese Persimmon"    , "Diospyros kaki"               },
{"Jatobá"                , "Hymenae coubaril"             },
{"Jelly Palm"            , "Butia capitata"               },
{"Jujube"                , "Ziziphus zizyphus"            },
{"Juniper berry"         , "Juniperus spp."               },
// K ------------------------------------------------------
{"Kabosu"                , "Citrus Sphaerocarpa"          },
{"Kaffir lime"           , "Citrus hystix"                },
{"Kahikatea"             , "Dacrycarpus dacrydioides"     },
{"Kakadu lime"           , "Citrus gracilis"              },
{"Kakadu plum"           , "Terminalia ferdinandiana"     },
{"Kandis"                , "Garcinia forbesii"            },
{"Kapok"                 , "Ceiba pentandra"              },
{"Karkalla"              , "Carpobrotus rossii"           },
{"Karonda"               , "Carissa carandas"             },
{"Kei apple"             , "Dovyalis caffra"              },
{"Keppel fruit"          , "Stelechocarpus burakol"       },
{"Keule"                 , "Gomortega keule"              },
{"Key Lime"              , "Citrus aurantifolia"          },
{"Kitembilla"            , "Dovyalis hebecarpa"           },
{"Kiwifruit"             , "Actinida spp."                },
{"Kumquat"               , "Fortunella spp."              },
{"Kundong"               , "Garcinia sp."                 },
{"Kutjera"               , "Solanum centrale"             },
{"Kwai Muk"              , "Artocarpus hypargyraea"       },
// L ------------------------------------------------------
{"Lady apple"            , "Syzygium suborbiculare"       },
{"Lakoocha"              , "Artocarpus lakoocha"          },
{"Langsat"               , "Lansium domesticum"           },
{"Lanzones"              , "Lansium domesticum"           },
{"Lapsi"                 , "Choerospondias axillaris"     },
{"Lardizabala"           , "Lardizabala biternata"        },
{"Lemon"                 , "Citrus limon"                 },
{"Lemon aspen"           , "Acronychia acidula"           },
{"Lillypilly"            , "Acmena spp."                  },
{"Limeberry"             , "Trifasia trifolia"            },
{"Lingonberry"           , "Vaccinium vitis-idaea"        },
{"Loganberry"            , "Rubus loganobaccus"           },
{"Longan"                , "Dimocarpus longan"            },
{"Loquat"                , "Eriobotrya japonica"          },
{"Louvi"                 , "Flacourtia inermis"           },
{"Lúcuma"                , "Pouteria campechiana"         },
{"Lychee"                , "Litchi chinensis"             },
// M ------------------------------------------------------
{"Ma-praang"             , "Bouea macrophylla"            },
{"Mabolo"                , "Diospyros discolor"           },
{"Macadamia"             , "Macadamia integrifolia"       },
{"Madrono"               , "Rheedia acuminata"            },
{"Malabar plum"          , "Syzygium jambos"              },
{"Malay Apple"           , "Syzygium malaccense"          },
{"Mamey"                 , "Pouteria sapota"              },
{"Mammee Apple"          , "Mammea americana"             },
{"Mamoncillo"            , "Melicoccus bijugatus"         },
{"Mandarin"              , "Citrus reticulata"            },
{"Mangaba"               , "Hancornia speciosa"           },
{"Mango"                 , "Mangifera indica"             },
{"Mangosteen"            , "Garcinia mangostana"          },
{"Manila tamarind"       , "Pithecellobium dulce"         },
{"Manoao"                , "Manoao colensoi"              },
{"Maqui"                 , "Aristotelia chilensis"        },
{"Marula"                , "Sclerocarya birrea"           },
{"Mayan Breadnut"        , "Brosimum alicastrum"          },
{"Mayapple"              , "Podophyllum spp."             },
{"Maypop"                , "Passiflora incarnata"         },
{"Medlar"                , "Mespilus germanica"           },
{"Meiwa Kumquat"         , "Fortunella japonica"          },
{"Midyim"                , "Austromyrtus dulcis"          },
{"Miracle Fruit"         , "Synsepalum dulcificum"        },
{"Mock Strawberry"       , "Potentilla indica"            },
{"Monkey Jackruit"       , "Artocarpus rigidus"           },
{"Monkey Tamarind"       , "Inga edulis"                  },
{"Monstera"              , "Monstera deliciosa"           },
{"Montessa Granadilla"   , "Passiflora platyloba"         },
{"Mora Común"            , "Rubus adenotrichus"           },
{"More de Castilla"      , "Rubus glaucus"                },
{"Mortiño"               , "Vaccinium floribundum"        },
{"Mountain pepper"       , "Tasmannia spp."               },
{"Mountain Soursop"      , "Annona montana"               },
{"Mulberry"              , "Morus spp."                   },
{"Mundu"                 , "Garcinia dulcis"              },
{"Muntries"              , "Kunzea pomifera"              },
{"Muscadine"             , "Vitis rotundifolia"           },
// N ------------------------------------------------------
{"Naartjie"              , "Citrus reticulata"            },
{"Nagami Kumquat"        , "Fortunella margarita"         },
{"Nageia"                , "Nageia spp."                  },
{"Nance"                 , "Byrsonima crassifolia"        },
{"Nannyberry"            , "Viburnum spp."                },
{"Naranjilla"            , "Solanum quitoense"            },
{"Native currant"        , "Acrotriche depressa"          },
{"Native gooseberry"     , "Physalis minima"              },
{"Native raspberry"      , "Rubus parviflorus"            },
{"Neem"                  , "Azadirachta indica"           },
{"Néré"                  , "Parkia biglobosa"             },
{"Nonda plum"            , "Parinari nonda"               },
{"Noni"                  , "Morinda citrifolia; Rubiaceae"},
{"Nungu"                 , "Borassus flabellifer"         },
{"Nutmeg"                , "Myristica fragrans"           },
// O ------------------------------------------------------
{"Oil Palm"              , "Elaeis guineensis"            },
{"Orange"                , "Citrus sinensis"              },
{"Oregon grape"          , "Mahonia aquifolium"           },
{"Oroblanco"             , "Citrus paradisi"              },
{"Otaheite gooseberry"   , "Phyllanthus acidus"           },
// P ------------------------------------------------------
{"Palmyra Palm"          , "Borassus flabellifer"         },
{"Papaya"                , "Carica papaya"                },
{"Passion fruit"         , "Passiflora edulis"            },
{"Pawpaw"                , "Asimina triloba"              },
{"Peach palm"            , "Bactris gasipaes"             },
{"Peanut"                , "Arachis hypogaea"             },
{"Peanut butter fruit"   , "Bunchosia argentea"           },
{"Pear"                  , " "                            },
{"Pecan"                 , "Carya illinoinensis"          },
{"Pepino"                , "Solanum muricatum"            },
{"Pequi"                 , "Caryocar brasiliensis"        },
{"Peumo"                 , "Cryptocarya alba"             },
{"Pewa"                  , "Peach palm"                   },
{"Phalsa"                , "Grewia subinaequalis"         },
{"Pigeon plum"           , "Coccoloba diversifolia"       },
{"Pigface"               , "Carpobrotus glaucescens"      },
{"Pili Nut"              , "Canarium ovatum"              },
{"Pindo Palm"            , "Butia Capitata"               },
{"Pineapple"             , "Ananas comosus"               },
{"Pineapple guava"       , "Feijoa sellowiana"            },
{"Pistachio"             , "Pistacia vera"                },
{"Pitomba"               , "Eugenia luschnathiana"        },
{"Pois doux"             , "Inga edulis"                  },
{"Pomegranate"           , "Punica granatum"              },
{"Pomelo"                , "Citrus maxima"                },
{"Pommecythère"          , "Spondias cytherea"            },
{"Pommerac"              , "Eugenia malaccensis"          },
{"Pond-apple"            , "Annona glabra"                },
{"Prickly pear"          , "Opuntia spp."                 },
{"Pulasan"               , "Nephelium mutabile"           },
{"Pummelo"               , "Citrus grandis"               },
{"Pupunha"               , "Bactris gasipaes"             },
{"Purple apple-berry"    , "Billarderia longiflora"       },
{"Purple Guava"          , "Psidium rufum"                },
{"Purple Mombin"         , "Spondias purpurea"            },
// Q ------------------------------------------------------
{"Quandong"              , "Santalum acuminatum"          },
{"Queensland Ebony"      , "Diospyros humilis"            },
{"Quince"                , "Cydonia oblonga"              },
// R ------------------------------------------------------
{"Raisin tree"           , "Hovenia dulcis"               },
{"Rambutan"              , "Nephelium lappaceum"          },
{"Red granadilla"        , "Passiflora coccinea"          },
{"Red Mombin"            , "Spondias purpurea"            },
{"Red Mulberry"          , "Morus rubra"                  },
{"Rhubarb"               , "Rheum rhaponticum"            },
{"Riberry"               , "Syzygium luehmannii"          },
{"Rimu"                  , "Dacrydium cupressinum"        },
{"Rollinia"              , "Rollinia mucosa"              },
{"Rose Apple"            , "Syzygium jambos"              },
{"Rose hip"              , " "                            },
{"Rose-leaf Bramble"     , "Rubus rosifolius"             },
{"Rose myrtle"           , "Archirhodomyrtus beckleri"    },
{"Rough Shell Macadamia" , "Macadamia tetraphylla"        },
{"Rowan"                 , "Sorbus"                       },
// S ------------------------------------------------------
{"Safou"                 , "Dacryodes edulis"             },
{"Sageretia"             , "Sageretia theezans"           },
{"Saguaro"               , "Carnegiea gigantea"           },
{"Salak"                 , "Salacca edulis"               },
{"Salal"                 , "Gaultheria shallon"           },
{"Salmonberry"           , "Rubus spectabilis"            },
{"Sandpaper Fig"         , "Ficus coronata"               },
{"Santol"                , "Sandoricum koetjape"          },
{"Sapodilla"             , "Manilkara zapota"             },
{"Saskatoonberry"        , "Amelanchier alnifolia"        },
{"Saw Palmetto"          , "Serenoa repens"               },
{"Sea-buckthorn"         , "Hippophae rhamnoides"         },
{"Sea Grape"             , "Coccoloba uvifera"            },
{"Snow berry"            , "Gaultheria hispida"           },
{"Soncoya"               , "Annona diversifolia"          },
{"Service tree"          , "Sorbus domestica"             },
{"Soursop"               , "Annona muricata"              },
{"Southern Crabapple"    , "Malus angustifolia"           },
{"Spanish lime"          , "Melicoccus bijugatus"         },
{"Spanish tamarind"      , "Vangueria madagascariensis"   },
{"Spiny Monkey-orange"   , "Strychnos spinosa"            },
{"Star Apple"            , "Chrysophyllum cainito"        },
{"Strawberry"            , "Fragaria"                     },
{"Strawberry Guava"      , "Psidium littorale"            },
{"Sugar Apple"           , "Annona squamosa"              },
{"Surinam Cherry"        , "Eugenia uniflora"             },
{"Sweet apple-berry"     , "Billarderia cymosa"           },
{"Sweet Granadilla"      , "Passiflora ligularis"         },
{"Sweet Lemon"           , "Citrus limetta"               },
{"Sweetsop"              , "Annona squamosa"              },
{"Sycamore fig"          , "Ficus sycomorus"              },
// T ------------------------------------------------------
{"Tahitian apple"        , "Spondias dulcis"              },
{"Tamarillo"             , "Cyphomandra betacea"          },
{"Tamarind"              , "Tamarindus indica"            },
{"Tanjong"               , "Mimusops elengi"              },
{"Texas Persimmon"       , "Diospyros texana"             },
{"Thimbleberry"          , "Rubus parviflorus"            },
{"Tōtara"                , "Podocarpus totara"            },
{"Toyon"                 , "Heteromeles arbutifolia"      },
{"Tropical Almond"       , "Terminalia catappa"           },
// U ------------------------------------------------------
{"Ugni"                  , "Ugni molinae"                 },
// V ------------------------------------------------------
{"Vanilla"               , "Vanilla planifolia"           },
{"Velvet Tamarind"       , "Dialium indum"                },
// W ------------------------------------------------------
{"Wampee"                , "Clausena lansium"             },
{"Water Apple"           , "Syzygium aqueum"              },
{"Watermelon"            , "Citrullus lanatus"            },
{"Wax Gourd"             , "Benincasa hispida"            },
{"Wax jambu"             , "Syzygium samarangense"        },
{"White aspen"           , "Acronychia oblongifolia"      },
{"White Mulberry"        , "Morus alba"                   },
{"White Sapote"          , "Casimiroa edulis"             },
{"Wild grape"            , "Ampelocissus acetosa"         },
{"Wild orange"           , "Capparis mitchellii"          },
{"Wild peach"            , "Terminalia carpentariae"      },
{"Wild plum"             , "Buchanania obovata"           },
{"Wild plum"             , "Santalum lanceolatum"         },
{"Wild Mangosteen"       , "Garcinia indica"              },
{"Wineberry"             , "Rubus phoenicolasius"         },
{"Wolfberry"             , "Lycium barbarum"              },
{"Wongi"                 , "Manilkara kaukii"             },
{"Wood Apple"            , "Feronia limonia"              },
// Y ------------------------------------------------------
{"Yangmei"               , "Myrica rubra"                 },
{"Yantok"                , "Calamus manillensis"          },
{"Yellow Granadilla"     , "Passiflora edulis"            },
{"Yellow Mombin"         , "Spondias mombin"              },
{"Yellow plum"           , "Ximenia americana"            },
// Z ------------------------------------------------------
{"Zig Zag Vine"          , "Melodurum leichhardtii"       }};


static const char *goodname_vegetable[]={
// Leafy vegetables ----------------------------------------------
{"Amaranth"                    , "Amaranthus cruentus"           },
{"Arugula"                     , "Eruca sativa"                  },
{"Beet greens"                 , "Beta vulgaris"                 },
{"Bitterleaf"                  , "Vernonia calvoana"             },
{"Bok choy"                    , "Brassica rapa"                 },
{"Broccoli Rabe"               , "Brassica rapa"                 },
{"Brussels sprout"             , "Brassica oleracea"             },
{"Cabbage"                     , "Brassica oleracea"             },
{"Catsear"                     , "Hypochaeris radicata"          },
{"Celery"                      , "Apium graveolens"              },
{"Celtuce"                     , "Lactuca sativa"                },
{"Ceylon spinach"              , "Basella alba"                  },
{"Chard"                       , "Beta vulgaris"                 },
{"Chaya"                       , "Cnidoscolus aconitifolius"     },
{"Chickweed"                   , "Stellaria"                     },
{"Chicory"                     , "Cichorium intybus"             },
{"Chinese cabbage"             , "Brassica rapa"                 },
{"Chinese Mallow"              , "Malva verticillata"            },
{"Chrysanthemum leaves"        , "Chrysanthemum coronarium"      },
{"Collard greens"              , "Brassica oleracea"             },
{"Corn salad"                  , "Valerianella locusta"          },
{"Cress"                       , "Lepidium sativum"              },
{"Dandelion"                   , "Taraxacum officinale"          },
{"Endive"                      , "Cichorium endivia"             },
{"Epazote"                     , "Chenopodium ambrosioides"      },
{"Fat hen"                     , "Chenopodium album"             },
{"Fiddlehead"                  , "Pteridium aquilinum"           },
{"Fluted pumpkin"              , "Telfairia occidentalis"        },
{"Garden Rocket"               , "Eruca sativa"                  },
{"Golden samphire"             , "Inula crithmoides"             },
{"Good King Henry"             , "Chenopodium bonus-henricus"    },
{"Greater Plantain"            , "Plantago major"                },
{"Kai-lan"                     , "Brassica rapa"                 },
{"Kale"                        , "Brassica oleracea"             },
{"Komatsuna"                   , "Brassica rapa"                 },
{"Kuka"                        , "Adansonia"                     },
{"Lagos bologi"                , "fruticosum"                    },
{"Lamb's lettuce"              , "Valerianella locusta"          },
{"Land cress"                  , "Barbarea verna"                },
{"Lettuce"                     , "Lactuca sativa"                },
{"Lizard's tail"               , "Houttuynia cordata"            },
{"Melokhia"                    , "Corchorus olitorius"           },
{"Miner's Lettuce"             , "Claytonia perfoliata"          },
{"Mizuna greens"               , "Brassica rapa"                 },
{"Mustard"                     , "Sinapis alba"                  },
{"Napa cabbage"                , "Brassica rapa"                 },
{"New Zealand Spinach"         , "Tetragonia tetragonioides"     },
{"Orache"                      , "Atriplex hortensis"            },
{"Pak choy"                    , "Brassica rapa"                 },
{"Paracress"                   , "Acmella oleracea"              },
{"Pea sprouts"                 , "Pisum sativum"                 },
{"Poke"                        , "Phytolacca americana"          },
{"Radicchio"                   , "Cichorium intybus"             },
{"Samphire"                    , "Crithmum maritimum"            },
{"Sea beet"                    , "Beta vulgaris"                 },
{"Sea kale"                    , "Crambe maritima"               },
{"Sierra Leone bologi"         , "Crassocephalum"                },
{"Soko"                        , "Celosia argentea"              },
{"Sorrel"                      , "Rumex acetosa"                 },
{"Spinach"                     , "Spinacia oleracea"             },
{"Summer purslane"             , "Portulaca oleracea"            },
{"Swiss chard"                 , "Beta vulgaris"                 },
{"Tatsoi"                      , "Brassica rapa"                 },
{"Turnip greens"               , "Brassica rapa"                 },
{"Watercress"                  , "Nasturtium officinale"         },
{"Water spinach"               , "Ipomoea aquatica"              },
{"Winter purslane"             , "Claytonia perfoliata"          },
{"Yarrow"                      , "Achillea millefolium"          },
// Vegetables that are fruits ------------------------------------
{"Avocado"                     , "Persea americana"              },
{"Bell pepper"                 , "Capsicum annuum"               },
{"Bitter melon"                , "Momordica charantia"           },
{"Courgette"                   , "Cucurbita pepo"                },
{"Cucumber"                    , "Cucumis sativus"               },
{"Ivy Gourd"                   , "Coccinia grandis"              },
{"Eggplant"                    , "Solanum melongena"             },
{"Aubergine"                   , "Solanum melongena"             },
{"Pumpkin"                     , "Cucurbita"                     },
{"Squash"                      , "Cucurbita"                     },
{"Maize"                       , "Zea mays"                      },
{"Sweet pepper"                , "Capsicum annuum"               },
{"Tinda"                       , "Praecitrullus fistulosus"      },
{"Tomatillo"                   , "Physalis philadelphica"        },
{"Tomato"                      , "Solanum lycopersicum"          },
{"Winter melon"                , "Benincasa hispida"             },
{"West Indian gherkin"         , "Cucumis anguria"               },
{"Zucchini"                    , "Cucurbita pepo"                },
// Flowers and flower buds ---------------------------------------
{"Artichoke"                   , "Cynara cardunculus"            },
{"Broccoli"                    , "Brassica oleracea"             },
{"Cauliflower"                 , "Brassica oleracea"             },
{"Courgette flowers"           , "Cucurbita"                     },
{"Squash blossoms"             , "Cucurbita"                     },
// Podded vegetables (legumes) -----------------------------------
{"American groundnut"          , "Apios americana"               },
{"Azuki bean"                  , "Vigna angularis"               },
{"Black-eyed pea"              , "Vigna unguiculata"             },
{"Chickpea"                    , "Cicer arietinum"               },
{"Common bean"                 , "Phaseolus vulgaris"            },
{"Drumstick"                   , "Moringa oleifera"              },
{"Dolichos bean"               , "Lablab purpureus"              },
{"Fava bean"                   , "Vicia faba"                    },
{"Garbanzo"                    , "Cicer arietinum"               },
{"Green bean"                  , "Phaseolus vulgaris"            },
{"Guar"                        , "Cyamopsis tetragonoloba"       },
{"Gumbo"                       , "Abelmoschus esculentus"        },
{"Horse gram"                  , "Macrotyloma uniflorum"         },
{"Indian pea"                  , "Lathyrus sativus"              },
{"Lentil"                      , "Lens culinaris"                },
{"Lima Bean"                   , "Phaseolus lunatus"             },
{"Moth bean"                   , "Vigna acontifolia"             },
{"Mung bean"                   , "Vigna radiata"                 },
{"Okra"                        , "Abelmoschus esculentus"        },
{"Pea"                         , "Pisum sativum"                 },
{"Peanut"                      , "Arachis hypogaea"              },
{"Pigeon pea"                  , "Cajanus cajan"                 },
{"Ricebean"                    , "Vigna umbellata"               },
{"Runner bean"                 , "Phaseolus coccineus"           },
{"Snap pea"                    , "Pisum sativum var. macrocarpon"},
{"Snow pea"                    , "Pisum sativum var. saccharatum"},
{"Soybean"                     , "Glycine max"                   },
{"Tarwi"                       , "Lupinus mutabilis"             },
{"Tepary bean"                 , "Phaseolus acutifolius"         },
{"Urad bean"                   , "Vigna mungo"                   },
{"Velvet bean"                 , "Mucuna pruriens"               },
{"Winged bean"                 , "Psophocarpus tetragonolobus"   },
{"Yardlong bean"               , "Vigna unguiculata"             },
// Bulb and stem vegetables --------------------------------------
{"Asparagus"                   , "Asparagus officinalis"         },
{"Cardoon"                     , "Cynara cardunculus"            },
{"Celeriac"                    , "Apium graveolens"              },
{"Celery"                      , "Apium graveolens"              },
{"Elephant Garlic"             , "Allium ampeloprasum"           },
{"Florence fennel"             , "Foeniculum vulgare"            },
{"Garlic"                      , "Allium sativum"                },
{"Kohlrabi"                    , "Brassica oleracea"             },
{"Kurrat"                      , "Allium ampeloprasum"           },
{"Leek"                        , "Allium porrum"                 },
{"Lotus root"                  , "Nelumbo nucifera"              },
{"Nopal"                       , "Opuntia ficus-indica"          },
{"Onion"                       , "Allium cepa"                   },
{"Spring Onion"                , "Allium wakegi"                 },
{"Prussian asparagus"          , "Ornithogalum pyrenaicum"       },
{"Shallot"                     , "Allium cepa"                   },
{"Welsh onion"                 , "Allium fistulosum"             },
{"Wild leek"                   , "tricoccum"                     },
// Roots and tuberous vegetables ---------------------------------
{"Ahipa"                       , "Pachyrhizus ahipa"             },
{"Arracacha"                   , "Arracacia xanthorrhiza"        },
{"Bamboo shoot"                , "Bambusa vulgaris"              },
{"Beetroot"                    , "Beta vulgaris"                 },
{"Burdock"                     , "Arctium lappa"                 },
{"Broadleaf arrowhead"         , "Sagittaria latifolia"          },
{"Camas"                       , "Camassia"                      },
{"Canna"                       , "Canna"                         },
{"Carrot"                      , "Daucus carota"                 },
{"Cassava"                     , "Manihot esculenta"             },
{"Chinese artichoke"           , "Stachys affinis"               },
{"Daikon"                      , "Raphanus sativus"              },
{"Earthnut pea"                , "Lathyrus tuberosus"            },
{"Elephant Foot yam"           , "Amorphophallus paeoniifolius"  },
{"Ensete"                      , "Ensete ventricosum"            },
{"Ginger"                      , "Zingiber officinale"           },
{"Gobo"                        , "Arctium lappa"                 },
{"Hamburg parsley"             , "Petroselinum crispum"          },
{"Jerusalem artichoke"         , "Helianthus tuberosus"          },
{"Jícama"                      , "Pachyrhizus erosus"            },
{"Manioc"                      , "Manihot esculenta"             },
{"Mooli"                       , "Raphanus sativus"              },
{"Parsnip"                     , "Pastinaca sativa"              },
{"Pignut"                      , "Conopodium majus"              },
{"Plectranthus"                , "Plectranthus"                  },
{"Potato"                      , "Solanum tuberosum"             },
{"Prairie turnip"              , "Psoralea esculenta"            },
{"Radish"                      , "Raphanus sativus"              },
{"Horseradish"                 , "Armoracia rusticana"           },
{"Rutabaga"                    , "Brassica napus"                },
{"Salsify"                     , "Tragopogon porrifolius"        },
{"Scorzonera"                  , "Scorzonera hispanica"          },
{"Skirret"                     , "Sium sisarum"                  },
{"Swede"                       , "Brassica napus"                },
{"Sweet Potato or Kumara"      , "Ipomoea batatas"               },
{"Taro"                        , "Colocasia esculenta"           },
{"Ti"                          , "Cordyline fruticosa"           },
{"Tigernut"                    , "Cyperus esculentus"            },
{"Turnip"                      , "Brassica rapa"                 },
{"Ulluco"                      , "Ullucus tuberosus"             },
{"Water chestnut"              , "Eleocharis dulcis"             },
{"Yacón"                       , "sonchifolius"                  },
{"Yam"                         , "Dioscorea"                     },
// Sea vegetables ------------------------------------------------
{"Aonori"                      , "Monostroma"                    },
{"Carola"                      , "Callophyllis variegata"        },
{"Dabberlocks"                 , "Alaria esculenta"              },
{"Dillisk"                     , "Palmaria palmata"              },
{"Hijiki"                      , "Hizikia fusiformis"            },
{"Kombu"                       , "Laminaria japonica"            },
{"Laver"                       , "Porphyra"                      },
{"Mozuku"                      , "Cladosiphon okamuranus"        },
{"Nori"                        , "Porphyra"                      },
{"Ogonori"                     , "Gracilaria"                    },
{"Sea grape"                   , "Caulerpa"                      },
{"Sea kale"                    , "Crambe maritima"               },
{"Sea lettuce"                 , "Ulva lactuca"                  },
{"Wakame"                      , "Undaria pinnatifida"           }};


static const char *goodname_nuts[]={
// Tree nuts ---------------------------------------------
{"Acorn"                    , "Quercus"                  },
{"American beech"           , "Fagus grandifolia"        },
{"European beech"           , "Fagus sylvatica"          },
{"Breadnut"                 , "Brosimum alicastrum"      },
{"Candlenut"                , "Aleurites moluccana"      },
{"Chinese chestnut"         , "Castanea mollissima"      },
{"Sweet chestnut"           , "Castanea sativa"          },
{"American hazelnut"        , "Corylus americana"        },
{"Beaked hazel"             , "Corylus cornuta"          },
{"European hazelnut"        , "Corylus avellana"         },
{"Filbert"                  , "Corylus maxima)"          },
{"Siberian hazelnut"        , "Corylus heterophylla"     },
{"Johnstone River almond"   , "Elaeocarpus bancroftii"   },
{"Kola nut"                 , "Cola"                     },
{"Kurrajong"                , "Brachychiton"             },
{"Malabar chestnut"         , "Pachira aquatica"         },
{"Mongongo"                 , "Ricinodendron rautanenii" },
{"Palm nut"                 , "Elaeis guineensis"        },
{"Karuka"                   , "Pandanus"                 },
{"Planted karuka"           , "Pandanus julianettii"     },
{"Wild karuka"              , "Pandanus brosimos"        },
{"Red bopple nut"           , "Hicksbeachia pinnatifolia"},
{"Yellow walnut"            , "Beilschmiedia bancroftii" },
// Nut-like drupe seeds ----------------------------------
{"Almond"                   , "Prunus dulcis"            },
{"Australian cashew nut"    , "Semecarpus australiensis" },
{"Betel nut"                , "Areca catechu"            },
{"Borneo tallow nut"        , "Shorea"                   },
{"Canarium nut"             , "Canarium harveyi"         },
{"Chinese olive pit"        , "Canarium album"           },
{"Pili nut"                 , "Canarium ovatum"          },
{"Cashew"                   , "Anacardium occidentale"   },
{"Chilean hazel"            , "Gevuina avellana"         },
{"Coconut"                  , "Cocos nucifera"           },
{"Gabon nut"                , "Coula edulis"             },
{"Mockernut hickory"        , "Carya tomentosa"          },
{"Pecan"                    , "Carya illinoinensis"      },
{"Shagbark hickory"         , "Carya ovata"              },
{"Shellbark hickory"        , "Carya laciniosa"          },
{"Bush mango"               , "Irvingia gabonensis"      },
{"Ogbono nut"               , "Irvingia wombolu"         },
{"Jack nut"                 , "Artocarpus heterophyllus" },
{"Pekea nut"                , "Caryocar nuciferum"       },
{"Pistachio"                , "Pistacia vera L."         },
{"Black walnut"             , "Juglans nigra"            },
{"Butternut"                , "Juglans cinerea)"         },
{"English walnut"           , "Juglans regia"            },
{"Heartnut"                 , "Juglans aitlanthifolia"   },
// Nut-like gymnosperm seeds -----------------------------
{"Burrawang nut"            , "Macrozamia communis"      },
{"Ginkgo nut"               , "Ginkgo biloba"            },
{"Bunya nut"                , "Araucaria bidwillii"      },
{"Monkey-puzzle nut"        , "Araucaria araucana"       },
{"Paraná pine nut"          , "Araucaria angustifolia"   },
{"Pine nuts"                , "Pinus"                    },
{"Colorado pinyon"          , "Pinus edulis"             },
{"Mexican pinyon"           , "Pinus cembroides"         },
{"Single-leaf pinyon"       , "Pinus monophylla"         },
{"Pignolia nut"             , "Pinus pinea"              },
// Nut-like angiosperm seeds -----------------------------
{"Brazil nut"               , "Bertholletia excelsa"     },
{"Macadamia"                , "Macadamia"                },
{"Macadamia nut"            , "Macadamia tetraphylla"    },
{"Queensland macadamia nut" , "Macadamia integrifolia"   },
{"Paradise nut"             , "Lecythis usitata"         },
{"Peanut"                   , "Arachis hypogaea"         },
{"Soybean"                  , "Glycine max"              }};

static const char *goodname_spice[]={
// A ---------------------------------------------------
{"Ajwain"               , "Trachyspermum ammi"         },
{"Akudjura"             , "Solanum centrale"           },
{"Alexander"            , "Smyrnium olusatrum"         },
{"Alkanet"              , "Alkanna tinctoria"          },
{"Alligator pepper"     , "Aframomum danielli"         },
{"Allspice"             , "Pimenta dioica"             },
{"Angelica"             , "Angelica archangelica"      },
{"Anise"                , "Pimpinella anisum"          },
{"Aniseed myrtle"       , "Syzygium anisatum"          },
{"Annatto"              , "Bixa orellana"              },
{"Apple mint"           , "Mentha suaveolens"          },
{"Asafoetida"           , "Ferula assafoetida"         },
{"Asarabacca"           , "Asarum europaeum"           },
{"Avens"                , "Geum urbanum"               },
{"Avocado leaf"         , "Peresea americana"          },
// B ---------------------------------------------------
{"Barberry"             , "Berberis vulgaris"          },
{"Sweet basil"          , "Ocimum basilicum"           },
{"Lemon basil"          , "Ocimum × citriodorum"       },
{"Holy basil"           , "Ocimum tenuiflorum"         },
{"Bay leaf"             , "Laurus nobilis"             },
{"Boldo"                , "Peumus boldus"              },
{"Borage"               , "Borago officinalis"         },
{"Black cardamom"       , "Amomum subulatum"           },
{"Black mustard"        , "Brassica nigra"             },
{"Blue fenugreek"       , "Trigonella caerulea"        },
{"Brown mustard"        , "Brassica juncea"            },
// C ---------------------------------------------------
{"Calabash nutmeg"      , "Monodora myristica"         },
{"Calendula"            , "Calendula officinalis"      },
{"Camphor laurel"       , "Cinnamomum camphora"        },
{"Canelo"               , "Drimys winteri"             },
{"Caraway"              , "Carum carvi"                },
{"Cardamom"             , "Elettaria cardamomum"       },
{"Carob"                , "Ceratonia siliqua"          },
{"Catnip"               , "Nepeta cataria"             },
{"Cassia"               , "Cinnamomum aromaticum"      },
{"Cayenne pepper"       , "Capsicum annuum"            },
{"Celery seed"          , "Apium graveolens"           },
{"Chervil"              , "Anthriscus cerefolium"      },
{"Chicory"              , "Cichorium intybus"          },
{"Chili pepper"         , "Capsicum spp."              },
{"Chives"               , "Allium schoenoprasum"       },
{"Cicely"               , "Myrrhis odorata"            },
{"Cilantro"             , "Coriandrum sativum"         },
{"Indonesian cinnamon"  , "Cinnamomum burmannii"       },
{"Saigon cinnamon"      , "Cinnamomum loureiroi"       },
{"Ceylon cinnamon"      , "Cinnamomum verum"           },
{"White cinnamon"       , "Canella winterana"          },
{"Cinnamon myrtle"      , "Backhousia myrtifolia"      },
{"Clary"                , "Salvia sclarea"             },
{"Clove"                , "Syzygium aromaticum"        },
{"Coriander seed"       , "Coriandrum sativum"         },
{"Costmary"             , "Tanacetum balsamita"        },
{"Cuban oregano"        , "Plectranthus amboinicus"    },
{"Cubeb pepper"         , "Piper cubeba"               },
{"Cudweed"              , "Gnaphalium"                 },
{"Culantro"             , "Eryngium foetidum"          },
{"Cumin"                , "Cuminum cyminum"            },
{"Curry leaf"           , "Murraya koenigii"           },
{"Curry plant"          , "Helichrysum italicum"       },
// D ---------------------------------------------------
{"Dill seed"            , "graveolens"                 },
{"Dill herb"            , "Anethum graveolens"         },
// E ---------------------------------------------------
{"Elderflower"          , "Sambucus"                   },
{"Epazote"              , "Dysphania ambrosioides"     },
// F ---------------------------------------------------
{"Fennel"               , "Foeniculum vulgare"         },
{"Fenugreek"            , "Trigonella foenum-graecum"  },
{"Filé powder"          , "Sassafras albidum"          },
{"Fingerroot"           , "Boesenbergia rotunda"       },
// G ---------------------------------------------------
{"Galingale"            , "Cyperus"                    },
{"Garlic chives"        , "Allium tuberosum"           },
{"Garlic"               , "Allium sativum"             },
{"Ginger"               , "Zingiber officinale"        },
{"Torch ginger"         , "Etlingera elatior"          },
{"Golpar"               , "Heracleum persicum"         },
{"Grains of paradise"   , "Aframomum melegueta"        },
{"Grains of Selim"      , "Xylopia aethiopica"         },
// H ---------------------------------------------------
{"Horseradish"          , "rusticana"                  },
{"Hyssop"               , "Hyssopus officinalis"       },
// I ---------------------------------------------------
{"Indonesian bay leaf"  , "Syzygium polyanthum"        },
// J ---------------------------------------------------
{"Jasmine flower"       , "Jasminum"                   },
{"Jimbu"                , "Allium hypsistum"           },
{"Juniper berry"        , "Juniperus communis"         },
// K ---------------------------------------------------
{"Kaffir lime leaf"     , "Citrus hystrix"             },
{"Black cumin"          , "Bunium persicum"            },
{"Kawakawa seed"        , "Macropiper excelsum"        },
{"Keluak"               , "Pangium edule"              },
{"Kokam seed"           , "Garcinia indica"            },
{"Korarima"             , "Aframomum corrorima"        },
{"Koseret leaf"         , "Lippia adoensis"            },
// L ---------------------------------------------------
{"Lavender"             , "Lavandula"                  },
{"Lemon balm"           , "Melissa officinalis"        },
{"Lemongrass"           , "Cymbopogon citratus"        },
{"Lemon ironbark"       , "Eucalyptus staigeriana"     },
{"Lemon myrtle"         , "Backhousia citriodora"      },
{"Lemon verbena"        , "Lippia citriodora"          },
{"Lesser calamint"      , "Calamintha nepeta"          },
{"Licorice"             , "Glycyrrhiza glabra"         },
{"Linden flower"        , "Tilia"                      },
{"Lovage"               , "Levisticum officinale"      },
// M ---------------------------------------------------
{"Mace"                 , "Myristica fragrans"         },
{"Mahlab"               , "Prunus mahaleb"             },
{"Malabathrum"          , "Cinnamomum tamala"          },
{"Marjoram"             , "Origanum majorana"          },
{"Marsh mallow"         , "Althaea officinalis"        },
{"Mastic"               , "Pistacia lentiscus"         },
{"Mint"                 , "Mentha"                     },
{"Mountain horopito"    , "Pseudowintera colorata"     },
{"Musk mallow"          , "Abelmoschus moschatus"      },
{"Black mustard"        , "Brassica nigra"             },
{"Brown mustard"        , "Brassica juncea"            },
{"White mustard"        , "Sinapis alba"               },
// N ---------------------------------------------------
{"Njangsa"              , "Ricinodendron heudelotii"   },
{"Nutmeg"               , "Myristica fragrans"         },
// O ---------------------------------------------------
{"Olida"                , "Eucalyptus olida"           },
{"Oregano"              , "Origanum vulgare"           },
{"Orris root"           , "Iris germanica"             },
// P ---------------------------------------------------
{"Pandan flower"        , "Pandanus odoratissimus"     },
{"Pandan leaf"          , "Pandanus amaryllifolius"    },
{"Paprika"              , "Capsicum annuum"            },
{"Paracress"            , "Spilanthes acmella"         },
{"Parsley"              , "Petroselinum crispum"       },
{"Pepper"               , "Piper nigrum"               },
{"Dorrigo pepper"       , "Tasmannia stipitata"        },
{"Long pepper"          , "Piper longum"               },
{"Mountain pepper"      , "Tasmannia lanceolata"       },
{"Peppermint"           , "Mentha piperata"            },
{"Peppermint gum leaf"  , "Eucalyptus dives"           },
{"Peruvian pepper"      , "Schinus molle"              },
{"Brazilian pepper"     , "Schinus terebinthifolius"   },
// Q ---------------------------------------------------
{"Quassia"              , "Quassia amara"              },
// R ---------------------------------------------------
{"Ramsons"              , "Allium ursinum"             },
{"Rosemary"             , "Rosmarinus officinalis"     },
{"Rue"                  , "Ruta graveolens"            },
// S ---------------------------------------------------
{"Safflower"            , "Carthamus tinctorius"       },
{"Saffron"              , "Crocus sativus"             },
{"Sage"                 , "Salvia officinalis"         },
{"Saigon cinnamon"      , "Cinnamomum loureiroi"       },
{"Salad burnet"         , "Sanguisorba minor"          },
{"Salep"                , "Orchis mascula"             },
{"Sassafras"            , "Sassafras albidum"          },
{"Summer savory"        , "Satureja hortensis"         },
{"Winter savory"        , "Satureja montana"           },
{"Sorrel"               , "Rumex acetosa"              },
{"Sheep sorrel"         , "Rumex acetosella"           },
{"Spearmint"            , "Mentha spicata"             },
{"Spikenard"            , "Nardostachys grandiflora"   },
{"Star anise"           , "Illicium verum"             },
{"Sumac"                , "Rhus coriaria"              },
{"Sweet woodruff"       , "Galium odoratum"            },
{"Szechuan pepper"      , "Zanthoxylum piperitum"      },
// T ---------------------------------------------------
{"Tarragon"             , "dracunculus"                },
{"Thyme"                , "Thymus vulgaris"            },
{"Lemon thyme"          , "Thymus × citriodorus"       },
{"Turmeric"             , "Curcuma longa"              },
// V ---------------------------------------------------
{"Vanilla"              , "planifolia"                 },
{"Vietnamese balm"      , "Elsholtzia ciliata"         },
{"Vietnamese cinnamon"  , "Cinnamomum loureiroi"       },
{"Vietnamese coriander" , "Persicaria odorata"         },
{"Voatsiperifery"       , "Piper borbonense"           },
// W ---------------------------------------------------
{"Wasabi"               , "japonica"                   },
{"Water-pepper"         , "Polygonum hydropiper"       },
{"Watercress"           , "Rorippa nasturtium-aquatica"},
{"White mustard"        , "Sinapis alba"               },
{"Wild betel"           , "Piper sarmentosum"          },
{"Wild thyme"           , "Thymus serpyllum"           },
{"Willow herb"          , "Epilobium parviflorum"      },
{"Winter savory"        , "Satureja montana"           },
{"Wintergreen"          , "Gaultheria procumbens"      },
{"Wood avens"           , "Geum urbanum"               },
{"Woodruff"             , "Galium odoratum"            },
{"Wormwood"             , "Artemisia absinthium"       },
// Y ---------------------------------------------------
{"Yellow mustard"       , "Sinapis alba"               }};


static const char *goodname_cereal[]={
// Cereals ---------------------------------------
{"Barley"            , "Hordeum vulgare"         },
{"Fonio"             , "Digitaria exilis"        },
{"Maize"             , "Zea mays"                },
{"Pearl Millet"      , "Pennisetum glaucum"      },
{"Oat"               , "Avena sativa"            },
{"Palmer's grass"    , "Distichlis palmeri"      },
{"Rice"              , "Oryza sativa"            },
{"Rye"               , "Secale cereale"          },
{"Sorghum"           , "Sorghum bicolor"         },
{"Spelt"             , "Triticum spelta"         },
{"Teff"              , "Eragrostis tef"          },
{"Bread wheat"       , "Triticum aestivum"       },
{"Durum wheat"       , "Triticum durum"          },
{"Wild rice"         , "Zizania aquatica"        },
// Pseudo-cereals --------------------------------
{"Breadnut"          , "Brosimum alicastrum"     },
{"Buckwheat"         , "Fagopyrum esculentum"    },
{"Cattail"           , "Typha latifolia"         },
{"Flax"              , "Linum usitatissimum"     },
{"Grain amaranth"    , "Amaranthus caudatus"     },
{"Kañiwa"            , "Chenopodium pallidicaule"},
{"Pitseed Goosefoot" , "Chenopodium berlandieri" },
{"Quinoa"            , "Chenopodium quinoa"      }};
