enum palette {
        C_BG       = 28,
        C_FG       = 29,
        BLACK      = 30,
        DGREY      = 31,
        GREY       = 32,
        LGREY      = 33,
        DBLUE      = 35,
        BLUE       = 36,
        LBLUE      = 37,
        DGREEN     = 38,
        GREEN      = 39,
        LGREEN     = 40,
        BROWN      = 41,
        ORANGE     = 42,
        YELLOW     = 43,
        RED        = 44,
        PINK       = 45,
        BEIGE      = 46,
        WHITE      = 47
};
enum extra_colors {
        SEAFOAM    = 48,
        SEAGREEN   = 49,
        YELLOWSAND = 50, 
        BROWNSAND  = 51,
        LWOOD      = 52,
        WOOD       = 53,
        SHADOW     = 54,
        PALE_BLUE  = 58,
        OFF_WHITE  = 59,
        DARK_RED   = 82 
};
/* FG_BG color pairs; odd ones are swaps of even ones. */
enum ramp_pairs {
        BLACK_DGREY   = 10,
        DGREY_BLACK   = 11,
        DGREY_GREY    = 12,
        GREY_DGREY    = 13,
        GREY_LGREY    = 14,
        LGREY_GREY    = 15,

        DGREY_DBLUE   = 16,
        DBLUE_DGREY   = 17,
        DBLUE_BLUE    = 18,
        BLUE_DBLUE    = 19,
        BLUE_LBLUE    = 20,
        LBLUE_BLUE    = 21,
        LBLUE_LGREY   = 22,
        LGREY_LBLUE   = 23,

        DGREY_DGREEN  = 24,
        DGREEN_DGREY  = 25,
        DGREEN_GREEN  = 26,
        GREEN_DGREEN  = 27,
        GREEN_LGREEN  = 28,
        LGREEN_GREEN  = 29,
        LGREEN_YELLOW = 30,
        YELLOW_LGREEN = 31,
        YELLOW_LGREY  = 32,
        LGREY_YELLOW  = 33,

        DGREY_BROWN   = 34,
        BROWN_DGREY   = 35,
        BROWN_ORANGE  = 36,
        ORANGE_BROWN  = 37,
        ORANGE_YELLOW = 38,
        YELLOW_ORANGE = 39,

        DGREY_RED     = 40,
        RED_DGREY     = 41,
        RED_PINK      = 42,
        PINK_RED      = 43,
        PINK_BEIGE    = 44,
        BEIGE_PINK    = 45,
        BEIGE_YELLOW  = 46,
        YELLOW_BEIGE  = 47,

        SEA_DARK      = 48,
        SEA_MED       = 49,
        SEA_LIGHT     = 50, 
        SEA_SHORE     = 51,
        BOAT_DEEP     = 52,
        SAIL_DEEP     = 53,

        CMP_BEIGE     = 54,
        CMP_RED       = 55,
        CMP_WHITE     = 56,
        CMP_ORANGE    = 57,
        CMP_GREEN     = 58,
        CMP_PINK      = 59,
        CMP_YELLOW    = 60,
        CMP_SHADOW    = 61,
        BOAT_WHITE    = 62,
        BOAT_WOOD     = 63,
        TREES         = 64,
        MONO          = 65,
        LAND          = 66,
        MENU          = 67,
        MENU_HINT     = 68,
        WARNING       = 69,
        WARNSHADOW    = 70
};
int init_palette(int);
